title: Abhilash Ramagiri
logo: /assets/img/headshot.png
description: >
  Experienced DevOps professional specializing in optimizing deployments, 
  empowering teams with efficient tools, and automating infrastructure for 
  high availability.
theme: jekyll-theme-minimal