title: Abhilash Ramagiri
logo: /assets/img/headshot.png
description: Experienced DevOps Engineer specializing in CI/CD, Infrastructure Automation, and containerization with 13+ years of success in multi-cloud environments. Committed to improving system performance and deployment efficiency through security and automation.
# show_downloads: true
theme: jekyll-theme-minimal
