title: Abhilash Ramagiri
logo: /assets/img/headshot.png
description: "Abhilash Ramagiri's personal portfolio"
# show_downloads: true
theme: jekyll-theme-minimal
social:
  github: https://github.com/iabhee
  linkedin: https://linkedin.com/in/ramagiriabhilash